### ISSUE TITLE
Suggestion to include video screen recording.

### ISSUE THREAD

**Issue by alusion** [jschx/poomf#16]
Using maim / slop http://tuxdiary.com/2014/10/17/maim-slop/ 
Have a flag to record video of a window or select rectangle and automatically upload to pomf.

example code:
eval $(slop); ffmpeg -f x11grab -s "$W"x"$H" -i :0.0+$X,$Y -f alsa -i pulse ~/.recording/slop_$(date "+%Y-%m-%d_%H:%M:%V").webm

**Comment by installgen2** [comment]
Not sure if I misunderstood something, but slop is for selection and maim is for image capturing, so if you plan to implement screen recording using FFMPEG, that wouldn't be using maim at all.

**Comment by alusion** [comment]
yeah MAIM wouldn't be used but ffmpeg x11grab could be used. I made an example bash script that uploads to teknik:  http://sprunge.us/XTah

worked great first few times but now it is recording at only a couple FPS now @_@

**Comment by installgen2** [comment]
I'd imagine it'd be easy enough to easy enough to add screen recording to poomf. I don't want to try it myself if someone else can, because it'd be too much of a mess to be accepted.

**Comment by jschx** [comment]
Usually the best way to record your screen is to record it to a normal video format (I use mkv) and then convert it to webm afterwards. It takes a while to do this conversion, that's why you're probably only getting a few FPS, it's trying to encode it on the fly. This is just my personal experience, I'm probably using the wrong terminology. I've had bad experiences just trying to record to webm, though.

Not sure if I could write a one-size-fits-all way to do this in the script though. People have different resolutions and will want to record at different bitrates, etc, and I don't know if there's a way I could implement this easily and without a lot of autodetection(?) stuff that I don't know anything about.

I'm open to the idea, though, I'd like to use this feature myself.
